version: '3'
services:
  tstp:
    build: ./
    container_name: tstp
    restart: unless-stopped
    networks:
      - proxy
    env_file: ./deployments/conf.env
    volumes:
      - ./res/:/app/res/
  tstp-proxy:
    image: nginx
    container_name: tstp-proxy
    volumes:
      - ./deployments/nginx-cache.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "${TRAEFIK_BASIC_AUTH_STRING}"
      - "traefik.http.routers.tstp.entrypoints=http"
      - "traefik.http.routers.tstp.rule=Host(`tstp.lukmert.de`)"
      - "traefik.http.routers.tstp.middlewares=https-redirect@file"
      - "traefik.http.routers.tstp-secure.entrypoints=https"
      - "traefik.http.routers.tstp-secure.rule=Host(`tstp.lukmert.de`)"
      - "traefik.http.routers.tstp-secure.tls=true"
      - "traefik.http.routers.tstp-secure.tls.certresolver=tls"
      - "traefik.http.routers.tstp-secure.service=tstp"
      - "traefik.http.services.tstp.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
